### PR TITLE
Nice-ified install instructions

### PR DESCRIPTION
**Pull request by ga-hegsvold**

### CODE REVIEW

**Comment by grove** [comment]
Could you please rebase this PR with master? The documentation can't be built currently.

**Comment by ga-hegsvold** [comment]
> Could you please rebase this PR with master? The documentation can't be built currently.

Does it work now?

**Comment by grove** [comment]
It does indeed. I've approved the PR.

**Comment by ga-hegsvold** [comment]
> It does indeed. I've approved the PR.

Goody! Should I merge, or will you or someone at your end do it?

**Comment by grove** [comment]
I've merged it now, but in general you can merge it yourself once it has been approved.

**Pull request merged**
