### PR TITLE
Update core-principles.rst

### PR DESCRIPTION
**Pull request by msauban**
suggestion for the definition of time series and reflexion on the canonical model

### CODE REVIEW

**Comment by msauban** [comment]
I think the section on the canonical model does not represent the intent accurately. While I agree it is an utopian goal to have an all encompassing eternal model, I do not believe it is the goal of the canonical model. I believe a good enough solution at a given time is achievable, I think the added value of Sesam's approach is on the flexibility front, and mechanically, on the cost front. The fact that a communication standard has to be redesigned every time a participating data format changes does not make the solution not viable, it makes it more expensive and prone to service unavailability.

**Comment by axelborgegmail** [comment]
> I think the section on the canonical model does not represent the intent accurately. While I agree it is an utopian goal to have an all encompassing eternal model, I do not believe it is the goal of the canonical model. I believe a good enough solution at a given time is achievable, I think the added value of Sesam's approach is on the flexibility front, and mechanically, on the cost front. The fact that a communication standard has to be redesigned every time a participating data format changes does not make the solution not viable, it makes it more expensive and prone to service unavailability.

I was trying to include this in the current version of the text. Can you try to update the text so we can evaluate the actual change you want?

**Comment by axelborgegmail** [comment]
> suggestion for the definition of time series and reflexion on the canonical model

I don't think I understand this change. A sensor reading represents a value in time, and I don't see in what case it can ever change?

**Comment by msauban** [comment]
> > suggestion for the definition of time series and reflexion on the canonical model
> 
> I don't think I understand this change. A sensor reading represents a value in time, and I don't see in what case it can ever change?

I found the wording could lead to think the data never (ever) changes, when it can evolve through time.

**Comment by msauban** [comment]
> > I think the section on the canonical model does not represent the intent accurately. While I agree it is an utopian goal to have an all encompassing eternal model, I do not believe it is the goal of the canonical model. I believe a good enough solution at a given time is achievable, I think the added value of Sesam's approach is on the flexibility front, and mechanically, on the cost front. The fact that a communication standard has to be redesigned every time a participating data format changes does not make the solution not viable, it makes it more expensive and prone to service unavailability.
> 
> I was trying to include this in the current version of the text. Can you try to update the text so we can evaluate the actual change you want?

I've updated the text. I removed notions of eternal solution.

**Comment by msauban** [comment]
> > suggestion for the definition of time series and reflexion on the canonical model
> 
> I don't think I understand this change. A sensor reading represents a value in time, and I don't see in what case it can ever change?

I think the inclusion of "industry wide data sharing" vs "intra organization" is very good.

**Review by axelborgegmail — COMMENTED** [review]
What about: "datamodel that is not native to any of the source systems, and lags behind

**Comment by grove** [comment]
Decided not to merge this PR. Create a new one if you want.

**Pull request closed without merging**
