### PR TITLE
Added docker-compose.yaml to .gitignore

### PR DESCRIPTION
**Pull request by kruand-sesam**
For people using docker to build the docs locally. 
Example of docker-compose file:
image

### CODE REVIEW

**Review by BaardBouvet — CHANGES_REQUESTED** [review]
Adding docker-compose.yaml to .gitignore doesn't make much sense and will just confuse anyone when adding that file to the repo. If you want to have local files that you don't check in, just don't add that to the Git index when you make commits.

**Comment by kruand-sesam** [comment]
I don't see how it will confuse people when it is defined in .gitignore - But OK you're the boss ;)

**Comment by BaardBouvet** [comment]
The convention, I think, is to add stuff to .gitignore when stuff is produced by tools and build process, typically temporary files. Can't you solve the problem here by just putting the docker compose file somewhere else? The confusion is not that it's in the .gitignore, but _why_ it's added to .gitignore. A comment in the .gitignore would make that easier.

**Comment by BaardBouvet** [comment]
As an example, the first line in the .gitignore is a good example on how to not do this.

**Comment by kruand-sesam** [comment]
I see your point Baard and I agree - Closing the PR :)

**Pull request closed without merging**
